version: '3'
services:
  server:
    # container_name: express-mongo
    restart: always
    build: .
    ports: 
      - 80:8080
    volumes: 
      - ./src:/app/src
    depends_on:
      - "database"
    links:
      - database
  database:
    image: mongo
    ports: 
      - "2017:27017"
    